### ISSUE TITLE
Possible Compability issue with ShowCase and other mods. 

### ISSUE THREAD

**Issue by Zelioth** [starforcraft/Showcase-Item#1]
I can the creator and maintainer of Friends United. A mod pack for 1.19.2. We have right under 500 mods and try to keep things as stable as possible while also working with mod creators to get things fixed or just find issues that can be annoying or not even noticed in smaller packs. 

I seen that you updated ShowCase-Item and wanted to add it to my pack for the next update I'm working on but it doesn't seem to work and I am not sure what the compatibility issue is. I am sure some mod that is in our pack just doesn't like being installed next to it so I figured I would install showcase, generate some logs and debugs and share them with you in hopes that you could find a solution to an issue that may or may not affect smaller or mid size packs. 

Information 
Minecraft - 1.19.2
Forge - 43.2.1

Logs 
[latest.log](https://github.com/starforcraft/Showcase-Item/files/10292545/latest.log)
[debug.log](https://github.com/starforcraft/Showcase-Item/files/10292546/debug.log)

**Comment by Zelioth** [comment]
[crash-2022-12-23_00.17.00-client.txt](https://github.com/starforcraft/Showcase-Item/files/10292587/crash-2022-12-23_00.17.00-client.txt)

**Comment by starforcraft** [comment]
If you already have Quark installed, why did you add this mod too?

**Comment by Zelioth** [comment]
Because quark doesn't add this feature to my knowledge? I have quark, and have tested the shift T chat feature and it makes a white plain, no info text appear in chat. I'd like the info, data, and attributes to show also.

**Comment by starforcraft** [comment]
Update Quark
