### ISSUE TITLE
[showcaseitem-1.20.1-1.0] Icon is y-shifted one whole character higher

### ISSUE THREAD

**Issue by MrNovado** [starforcraft/Showcase-Item#2]
## Example 1:
![showcase_y_shift_give_bug](https://github.com/starforcraft/Showcase-Item/assets/4604289/6dafb331-29fd-4529-8396-a3fc62af42af)

## Example 2:
![showcase_y_shift_bug](https://github.com/starforcraft/Showcase-Item/assets/4604289/5bcaf054-a8fa-46fb-9643-c6eaa36f1115)

**Comment by MrNovado** [comment]
A weird stitching issue with an outdated ui recourcepack 🤔

**Comment by MrNovado** [comment]
Hm, sorry, it appears the issue is flaky and is appears and disappears from time-to-time in the same game.
No idea why it happens: one time you can start the game and everything is fine and just a few minutes later and it breaks.

**Comment by MrNovado** [comment]
Current incompatibility suspect is Fuzs' `OverflowingBars-v8.0.0-1.20.1-Forge`

**Comment by starforcraft** [comment]
[showcaseitem-1.20.1-1.1.jar.zip](https://github.com/starforcraft/Showcase-Item/files/13965312/showcaseitem-1.20.1-1.1.jar.zip)
Can you please try this version out? and let me know if it fixed the issue

**Comment by MrNovado** [comment]
I've since upped several versions of my modpack and I use your mod reliably 😃 
And I can confidently say `OverflowingBars` was the culprit behind the issue here.

Still, I'll re-check your new version on a clean pack with `OverflowingBars` sometime (today?) this week.

**Comment by MrNovado** [comment]
Unfortunately, the game crashes on startup.

Minecraft: 1.20.1
Forge: 47.2.0
OverflowingBars-v8.0.0-1.20.1
PuzzlesLib-v8.1.13-1.20.1
showcaseitem-1.20.1-1.1

Disabling `showcaseitem` fixes the crash.
Crash logs are non-sensical.

Last log-line before the crash
> [Render thread/WARN]: Error loading class: com/llamalad7/mixinextras/injector/wrapoperation/Operation (java.lang.ClassNotFoundException: com.llamalad7.mixinextras.injector.wrapoperation.Operation)

Crash-log (sanitized):
[crash-2024-01-18_11.37.52-client.txt](https://github.com/starforcraft/Showcase-Item/files/13972967/crash-2024-01-18_11.37.52-client.txt)

**Comment by MrNovado** [comment]
Launching with only `showcaseitem-1.20.1-1.1` also crashes the game.
The crash-log is the same.

**Comment by starforcraft** [comment]
[showcaseitem-1.20.1-1.1.jar.zip](https://github.com/starforcraft/Showcase-Item/files/14036727/showcaseitem-1.20.1-1.1.jar.zip)
Oh sorry about that. I should have tested it beforehand. Then can you please test this version?

**Comment by MrNovado** [comment]
The good news is your new version does not crash 😃 
The bad news, the issue is still there unfortunately.

Though, now I understand what's happening and how to reproduce the effect:

**Precognition**:

- Minecraft: 1.20.1
- Forge: 47.2.0
- OverflowingBars-v8.0.0-1.20.1
- PuzzlesLib-v8.1.13-1.20.1
- showcaseitem-1.20.1-1.1

**Cognition**:

1. Start the game in survival (cheats on)
2. Give yourself a golden apple `/give @a minecraft:golden_apple`
3. Notice how apple icon is rendered in chat (should be correct)
4. Eat the apple
5. Open the chat / or give yourself another apple
6. Notice how apple icon is y-shifted up one character

**Comment by MrNovado** [comment]
Note: without the `OverflowingBars` there's no issue

**Comment by starforcraft** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/showcase-item/files/5078249

**Comment by MrNovado** [comment]
Still reproduces for me /w the same repro steps as before but for `showcaseitem-1.20.1-1.1`  🤷 
Also it is now incompatible with `quark-4.0-434` [/w their --currently-bugged?-- item-showcasing feature turned off].
(but the prev. version  `showcaseitem-1.20.1-1.0` *IS* compatible)

So, I'm not pushing/advocating for this issue or anything, please do (or not) at your own discretion 🙇 ; I'll probably stay with `1.20.1-1.0` version from this point forward as this would be easier for me with my mess-of-a-modpack.

**Comment by starforcraft** [comment]
Now it really should be fixed and it also shouldn't crash together with Quark anymore https://legacy.curseforge.com/minecraft/mc-mods/showcase-item/files/5090810

**Comment by MrNovado** [comment]
Can confirm, seems like the issue is resolved 👍  Thanks!
