### ISSUE TITLE
How to change the color of the nickname output in the chat?

### ISSUE THREAD

**Issue by Loker541** [starforcraft/Showcase-Item#4]
I write in this format, the color of the nickname remains white:

{
  "key.showcaseitem.showcaseitem": "Шифтануть предмет",
  "showcaseitem.misc.shared_item": "§8%s§f Демонстрирует предмет:§6 "
}

**Comment by starforcraft** [comment]
It's not possible like that. You will have to change the code here: https://github.com/starforcraft/Showcase-Item/blob/7e34f5f2725b1d68e98d7631639ff098fd07c690/src/main/java/com/ultramega/showcaseitem/ShowcaseItemFeature.java#L104 and write `comp.setStyle(comp.getStyle().withColor(FastColor.ARGB32.color(r, g, b)))`

**Comment by Loker541** [comment]
My Minecraft version is 1.19.2, when building from the sources available here, version showcaseitem-1.21-1.0.0 comes out, the mod does not work in the game after building (the build is successful). Are the available sources relevant for version 1.19.2?

Thanks

> It's not possible like that. You will have to change the code here:
> 
> https://github.com/starforcraft/Showcase-Item/blob/7e34f5f2725b1d68e98d7631639ff098fd07c690/src/main/java/com/ultramega/showcaseitem/ShowcaseItemFeature.java#L104
> 
> and write `comp.setStyle(comp.getStyle().withColor(FastColor.ARGB32.color(r, g, b)))`

**Comment by starforcraft** [comment]
Then just switch to the 1.19.2 branch: https://github.com/starforcraft/Showcase-Item/blob/8837401ee262ed9ae6a5aac177f5d749c5da7c5f/src/main/java/com/Ultramega/ShowcaseItem/ShowcaseItemFeature.java#L101
