### ISSUE TITLE
buggy image offset

### ISSUE THREAD

**Issue by VaporeonScripts** [starforcraft/Showcase-Item#5]
![image](https://github.com/user-attachments/assets/d51dcf70-c5c9-4fcb-ad2a-edd90fd898dd)

**Comment by VaporeonScripts** [comment]
neoforge 1.21.1 .76

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/d894ba2b-d96f-466f-a4c7-a3ad37ecf5a2)

**Comment by starforcraft** [comment]
Is this the newest version (1.0.1)?

**Comment by VaporeonScripts** [comment]
yup

**Comment by starforcraft** [comment]
Hmm weird, I will archive that version then

**Comment by VaporeonScripts** [comment]
alright, hope you find a fix! :grinning:

**Comment by VaporeonScripts** [comment]
any news? i'm still kinda encountering it

<img width="817" height="69" alt="Image" src="https://github.com/user-attachments/assets/81589f9d-7e3c-4400-90c9-4a5538d7b067" />

**Comment by VaporeonScripts** [comment]
more evident here:

<img width="516" height="55" alt="Image" src="https://github.com/user-attachments/assets/6c761976-288f-46f9-9971-4d10982e2847" />
